// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// OwnersGroup is an autogenerated mock type for the OwnersGroup type
type OwnersGroup struct {
	mock.Mock
}

// Resource provides a mock function with given fields: g
func (_m *OwnersGroup) Resource(g *echo.Group) {
	_m.Called(g)
}

type mockConstructorTestingTNewOwnersGroup interface {
	mock.TestingT
	Cleanup(func())
}

// NewOwnersGroup creates a new instance of OwnersGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOwnersGroup(t mockConstructorTestingTNewOwnersGroup) *OwnersGroup {
	mock := &OwnersGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
