// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "franchises-system/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// Companies is an autogenerated mock type for the Companies type
type Companies struct {
	mock.Mock
}

// CreateCompany provides a mock function with given fields: ctx, company
func (_m *Companies) CreateCompany(ctx context.Context, company dto.Company) error {
	ret := _m.Called(ctx, company)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCompanyByID provides a mock function with given fields: ctx, ID
func (_m *Companies) GetCompanyByID(ctx context.Context, ID int64) (dto.Company, error) {
	ret := _m.Called(ctx, ID)

	var r0 dto.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (dto.Company, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) dto.Company); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Get(0).(dto.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCompanies interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompanies creates a new instance of Companies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompanies(t mockConstructorTestingTNewCompanies) *Companies {
	mock := &Companies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
