// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// Companies is an autogenerated mock type for the Companies type
type Companies struct {
	mock.Mock
}

// CreateCompany provides a mock function with given fields: c
func (_m *Companies) CreateCompany(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCompanies interface {
	mock.TestingT
	Cleanup(func())
}

// NewCompanies creates a new instance of Companies. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCompanies(t mockConstructorTestingTNewCompanies) *Companies {
	mock := &Companies{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
