// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// Franchises is an autogenerated mock type for the Franchises type
type Franchises struct {
	mock.Mock
}

// CreateFranchise provides a mock function with given fields: c
func (_m *Franchises) CreateFranchise(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFranchiseByName provides a mock function with given fields: c
func (_m *Franchises) GetFranchiseByName(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFranchisesByCompanyOwner provides a mock function with given fields: c
func (_m *Franchises) GetFranchisesByCompanyOwner(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFranchises interface {
	mock.TestingT
	Cleanup(func())
}

// NewFranchises creates a new instance of Franchises. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFranchises(t mockConstructorTestingTNewFranchises) *Franchises {
	mock := &Franchises{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
