// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// Owners is an autogenerated mock type for the Owners type
type Owners struct {
	mock.Mock
}

// CreateOwner provides a mock function with given fields: c
func (_m *Owners) CreateOwner(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewOwners interface {
	mock.TestingT
	Cleanup(func())
}

// NewOwners creates a new instance of Owners. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOwners(t mockConstructorTestingTNewOwners) *Owners {
	mock := &Owners{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
